# Generated by Django 6.0.3 on 2026-03-11 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_branch_enrollee'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollee',
            name='tracking_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
